### ISSUE TITLE
Field type Text in CMA is less specific than in the back-end app

### ISSUE THREAD

**Issue by selo-ecube** [contentful/contentful-management.java#49] opened 2016-03-30 08:36 UTC
In the CMA API I can use Constants.CMAFieldType.Text to make a field of type text, but in the back-end app (https://app.contentful.com/) there are Short Text and Long Text field types.

When I created a field of type Text via the CMA API, I've at times seen it appear as Short Text, at other times as Long Text, without obvious reasons for the change. This seems to be problematic because I have multiple contents types with a slug field, which should have the same type.

When created manually, the type is Short Text and I am able to request entries via the CDA API, with the equals operator ( .where("slug", slug) ). When Contentful decides to create a field of type Long Text, the CDA API complains that the equals operator cannot be applied on fields.slug.de-DE because it has type Text.

**Comment by mariobodemann** [comment] 2016-03-30 15:33
Hey,

for the `short text` four *slugs* I recommend using [`Constants.CMAFieldType.Symbol`](https://www.contentful.com/developers/docs/references/field-type/) as those are querryable using *strict equality* and fit the purpose of a slug.

I just generated some random `ContentTypes`, trying to recreate the issue of the type not being consistent. Sadly I cannot reproduce the behaviour you described :( Can you give me some more details, and/or some code samples to look at? 

This sounds like a bug, either in the documentation or in our SDK, and I would be happy to fix that either way ... ;) 

Thank you for spotting this, I hope we can fix that issue together …

**Comment by selo-ecube** [comment] 2016-03-31 10:10
Thanks for your help! I also tried to re-produce the behaviour but did not succeed. Most likely I lost track of things when I switched from a manually-created content type (which had Short Text fields only) to the programmatically generated one (which had Text/Long Text fields only).

Maybe it was not a great idea of mine to stick to the Java API (having no JavaDoc for Constants.CMAFieldType.*) and the App (using the terms Long Text and Short Text) instead of reading the REST API docs (that explain that the Symbol type in the API is not a single character, but a Short Text in the terms of the App and the Text type in the API is the Long Text in the terms of the App).

Thanks again and sorry for causing some confusion/overhead :-/.

**Comment by mariobodemann** [comment] 2016-03-31 10:53
Hey,

thank you for your input. I put writing more javadoc for the CMA SDK on our roadmap to avoid ambiguity in future. 

Thank you for your feedback. We really appreciate this kind of feedback, it helps us making the SDK as friction less as possible. If you feel there is more to be improved, feel free to create another issue, for now I'll close this one.

Thanks, 
Mario

**Closed by mariobodemann** 2016-03-31 10:53 UTC
